// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/DealUnloker/mockzoo/internal/entity"
	repo "github.com/DealUnloker/mockzoo/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockPetRepo is a mock of PetRepo interface.
type MockPetRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPetRepoMockRecorder
	isgomock struct{}
}

// MockPetRepoMockRecorder is the mock recorder for MockPetRepo.
type MockPetRepoMockRecorder struct {
	mock *MockPetRepo
}

// NewMockPetRepo creates a new mock instance.
func NewMockPetRepo(ctrl *gomock.Controller) *MockPetRepo {
	mock := &MockPetRepo{ctrl: ctrl}
	mock.recorder = &MockPetRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPetRepo) EXPECT() *MockPetRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPetRepo) Create(ctx context.Context, pet *entity.Pet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPetRepoMockRecorder) Create(ctx, pet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPetRepo)(nil).Create), ctx, pet)
}

// Delete mocks base method.
func (m *MockPetRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPetRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPetRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockPetRepo) GetByID(ctx context.Context, id int64) (entity.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPetRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPetRepo)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPetRepo) List(ctx context.Context, filter repo.PetFilter) ([]entity.Pet, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.Pet)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPetRepoMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPetRepo)(nil).List), ctx, filter)
}

// Reset mocks base method.
func (m *MockPetRepo) Reset(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockPetRepoMockRecorder) Reset(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockPetRepo)(nil).Reset), ctx)
}

// Update mocks base method.
func (m *MockPetRepo) Update(ctx context.Context, pet *entity.Pet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pet)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPetRepoMockRecorder) Update(ctx, pet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPetRepo)(nil).Update), ctx, pet)
}
