// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/DealUnloker/mockzoo/internal/entity"
	usecase "github.com/DealUnloker/mockzoo/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockPet is a mock of Pet interface.
type MockPet struct {
	ctrl     *gomock.Controller
	recorder *MockPetMockRecorder
	isgomock struct{}
}

// MockPetMockRecorder is the mock recorder for MockPet.
type MockPetMockRecorder struct {
	mock *MockPet
}

// NewMockPet creates a new mock instance.
func NewMockPet(ctrl *gomock.Controller) *MockPet {
	mock := &MockPet{ctrl: ctrl}
	mock.recorder = &MockPetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPet) EXPECT() *MockPetMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPet) Create(ctx context.Context, input usecase.CreatePetInput) (entity.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(entity.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPetMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPet)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockPet) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPetMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPet)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockPet) GetByID(ctx context.Context, id int64) (entity.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPetMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPet)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPet) List(ctx context.Context, filter usecase.PetFilter) ([]entity.Pet, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.Pet)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPetMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPet)(nil).List), ctx, filter)
}

// Reset mocks base method.
func (m *MockPet) Reset(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockPetMockRecorder) Reset(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockPet)(nil).Reset), ctx)
}

// Update mocks base method.
func (m *MockPet) Update(ctx context.Context, id int64, input usecase.UpdatePetInput) (entity.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(entity.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPetMockRecorder) Update(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPet)(nil).Update), ctx, id, input)
}
